# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(881, 429)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 866, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(4)
        self.mainVLayout.setObjectName("mainVLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.textBut.setFont(font)
        self.textBut.setStyleSheet("    QPushButton{\n"
"        border: 2px  solid  rgb(0, 0, 0);\n"
"        background: rgb(255, 255, 255);\n"
"        border-style: outset;\n"
"        border-width: 1px 1px 1px 1px;\n"
"        border-radius: 0px;\n"
"        color: black;\n"
"        padding: 5px 5px 5px 5px;   \n"
"    }\n"
"QPushButton:checked {\n"
"border-style: inset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #90D5FF\n"
");\n"
"}\n"
"QPushButton:disabled {\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
");\n"
"}\n"
"")
        self.textBut.setCheckable(True)
        self.textBut.setAutoExclusive(True)
        self.textBut.setObjectName("textBut")
        self.horizontalLayout.addWidget(self.textBut)
        self.contBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.contBut.setFont(font)
        self.contBut.setStyleSheet("    QPushButton{\n"
"        border: 2px  solid  rgb(0, 0, 0);\n"
"        background: rgb(255, 255, 255);\n"
"        border-style: outset;\n"
"        border-width: 1px 1px 1px 0px;\n"
"        border-radius: 0px;\n"
"        color: black;\n"
"        padding: 5px 5px 5px 5px;   \n"
"    }\n"
"QPushButton:checked {\n"
"border-style: inset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #90D5FF\n"
");\n"
"}\n"
"QPushButton:disabled {\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
");\n"
"}\n"
"")
        self.contBut.setCheckable(True)
        self.contBut.setAutoExclusive(True)
        self.contBut.setObjectName("contBut")
        self.horizontalLayout.addWidget(self.contBut)
        self.lineBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.lineBut.setFont(font)
        self.lineBut.setStyleSheet("    QPushButton{\n"
"        border: 2px  solid  rgb(0, 0, 0);\n"
"        background: rgb(255, 255, 255);\n"
"        border-style: outset;\n"
"        border-width: 1px 1px 1px 0px;\n"
"        border-radius: 0px;\n"
"        color: black;\n"
"        padding: 5px 5px 5px 5px;   \n"
"    }\n"
"QPushButton:checked {\n"
"border-style: inset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #90D5FF\n"
");\n"
"}\n"
"QPushButton:disabled {\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
");\n"
"}\n"
"")
        self.lineBut.setCheckable(True)
        self.lineBut.setAutoExclusive(True)
        self.lineBut.setObjectName("lineBut")
        self.horizontalLayout.addWidget(self.lineBut)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mainVLayout.addLayout(self.horizontalLayout)
        self.tempLayout = QtWidgets.QVBoxLayout()
        self.tempLayout.setObjectName("tempLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tempLayout.addItem(spacerItem1)
        self.mainVLayout.addLayout(self.tempLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBut.setText(_translate("Form", "Text Output"))
        self.contBut.setText(_translate("Form", "Contour Graph"))
        self.lineBut.setText(_translate("Form", "Line Cut Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
