# Upload SUN-DIC to PyPi when a tag is pushed
name: Upload SUN-DIC to PyPi
permissions:
  contents: read
  pull-requests: write

on:
  push:
    tags:
      - '*' # use 'v*' instead to only match tags like v1.2.3

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tool
        run: python3 -m pip install --user build

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  pypi-publish:
    name: Publish SUN-DIC to PyPi
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/SUN-DIC

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish SUN-DIC to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Ensure you set PYPI_API_TOKEN as a repository secret
          token: ${{ secrets.PYPI_API_TOKEN }}